---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-deployment-fork
  - name: bosh-deployment-src
  - name: bosh-cpi-src
run:
  path: bosh-cpi-src/ci/pipelines/update-bosh-deployment/tasks/pull-request.sh
params:
  github_token: ""
  head_repo: ""
  head_owner: ""
  head_branch: ""
  base_repo: ""
  base_branch: ""
  pr_message: ""
