---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: boshcpi/openstack-cpi-release
inputs:
  - name: bosh-cpi-src
  - name: bosh-deployment-src
  - name: bosh-openstack-cpi-release
outputs:
  - name: bosh-deployment-fork
run:
  path: bosh-cpi-src/ci/pipelines/update-bosh-deployment/tasks/update-cpi-version.sh
